//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttacheCase.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttacheCase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AttacheCase5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AttacheCase5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AttacheCase {
            get {
                return ResourceManager.GetString("AttacheCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BreadcrumbsConfirmPassword {
            get {
                return ResourceManager.GetString("BreadcrumbsConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BreadcrumbsExecuteDecrypt {
            get {
                return ResourceManager.GetString("BreadcrumbsExecuteDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BreadcrumbsExecuteEncrypt {
            get {
                return ResourceManager.GetString("BreadcrumbsExecuteEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BreadcrumbsHome {
            get {
                return ResourceManager.GetString("BreadcrumbsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BreadcrumbsInputPassword {
            get {
                return ResourceManager.GetString("BreadcrumbsInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonTextBack {
            get {
                return ResourceManager.GetString("ButtonTextBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonTextCancel {
            get {
                return ResourceManager.GetString("ButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonTextOK {
            get {
                return ResourceManager.GetString("ButtonTextOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Academic License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageAcademicLicense {
            get {
                return ResourceManager.GetString("DialogMessageAcademicLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activate your academic license.
        ///Are you a student or an educator? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageAcademicUseLicense {
            get {
                return ResourceManager.GetString("DialogMessageAcademicUseLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access to the file has been denied.
        ///Move to a place (eg Desktop) where you can read and write files and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageAccessDeny {
            get {
                return ResourceManager.GetString("DialogMessageAccessDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The external configuration file (_AtcCase.ini) could not be loaded. AttacheCase will now exit.
        ///To enable settings, delete &quot;_AtcCase.ini&quot; or approve loading it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageAppExitWithIniFileFailedToLoad {
            get {
                return ResourceManager.GetString("DialogMessageAppExitWithIniFileFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To enable this setting, you will need to restart the AttacheCase.
        ///Do you restart AttacheCase now? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageApplicationRestart {
            get {
                return ResourceManager.GetString("DialogMessageApplicationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This encrypted file is broken. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageAtcFileBroken {
            get {
                return ResourceManager.GetString("DialogMessageAtcFileBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Both Random setting and Zero setting are not able to set to zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageBothRandomAndZeroNotZero {
            get {
                return ResourceManager.GetString("DialogMessageBothRandomAndZeroNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The encrypted file has been broken because it exceeded the limit number of inputting password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageBroken {
            get {
                return ResourceManager.GetString("DialogMessageBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The encrypted file has already been destroyed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageBrokenAlready {
            get {
                return ResourceManager.GetString("DialogMessageBrokenAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The broken token could not found. The file may not be an encrypted file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageBrokenDestroyNotFount {
            get {
                return ResourceManager.GetString("DialogMessageBrokenDestroyNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The self-executable file you create may exceed 4 GiB.The file may not work as an executable.Would you like to continue?
        ///(*It can be decrypted as an encrypted file even if it is not launched as an executable file.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageCreateSelfExecutableEileLargerThan4GiB {
            get {
                return ResourceManager.GetString("DialogMessageCreateSelfExecutableEileLargerThan4GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The RSA public or private key is in a different format or is not in XML file format.
        ///The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageCryptographicException {
            get {
                return ResourceManager.GetString("DialogMessageCryptographicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encrypted data not found. The file is broken.
        ///Decryption failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDataNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is invalid, or the encrypted file might have been broken. Decryption is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDecryptionError {
            get {
                return ResourceManager.GetString("DialogMessageDecryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified password file is not found in decryption. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDecryptionPasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDecryptionPasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove this commercial license? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDeleteCommercialLicense {
            get {
                return ResourceManager.GetString("DialogMessageDeleteCommercialLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete the encypted file(s) that are the source of the decryption? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDeleteEncryptedFiles {
            get {
                return ResourceManager.GetString("DialogMessageDeleteEncryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete the files and folders that are the source of the encrypted file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDeleteOriginalFilesAndFolders {
            get {
                return ResourceManager.GetString("DialogMessageDeleteOriginalFilesAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discard the loaded temporary settings and load the settings from the registry. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDicardTempSettingsAndLoadRegistry {
            get {
                return ResourceManager.GetString("DialogMessageDicardTempSettingsAndLoadRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A part of the file or directory cannot be found.
        ///The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDirectoryNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder to save is not found! Process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDirectoryNotFount {
            get {
                return ResourceManager.GetString("DialogMessageDirectoryNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Junction or symbolic link cannot be encrypted.
        ///The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDirReparsePoint {
            get {
                return ResourceManager.GetString("DialogMessageDirReparsePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are files or folders that be encrypted or decrypted, and they are mixed, they does not exists. So, AttacheCase can not determine which should encrypt or decrypt either. It stopped the process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDragAndDropMixedFiles {
            get {
                return ResourceManager.GetString("DialogMessageDragAndDropMixedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An attempt was made to access an unavailable drive or share.
        ///The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDriveNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDriveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag and drop the encrypted file here to decrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageDropEncryptedFileToDecrypt {
            get {
                return ResourceManager.GetString("DialogMessageDropEncryptedFileToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The encrypted file was deleted because the number of password entry errors exceeded the specified number of attempts. Once the application is closed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageEncryptedFileDeletedOverAttempts {
            get {
                return ResourceManager.GetString("DialogMessageEncryptedFileDeletedOverAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified password file is not found in encryption. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageEncryptionPasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageEncryptionPasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It contains the executable files in the decrypted file.
        ///Do you run the following file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageExecutableFile {
            get {
                return ResourceManager.GetString("DialogMessageExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The extension was not entered correctly or is an invalid value.
        ///Extensions must be entered as comma-separated values containing a period. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageExtensionInvalid {
            get {
                return ResourceManager.GetString("DialogMessageExtensionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File association was successful に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFileAssociationSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File association tool is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFileAssociationToolNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File association tool can be not launched. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFileAssociationToolNotLaunched {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationToolNotLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal file index is invalid in encrypted file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFileIndexInvalid {
            get {
                return ResourceManager.GetString("DialogMessageFileIndexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file in the following specified file&apos;s list can not be found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFileInFileListNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileInFileListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The character encoding of the following specified file is unknown that can not be read! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFileListEncodingUnknown {
            get {
                return ResourceManager.GetString("DialogMessageFileListEncodingUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following specified list file can not be found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFileListNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An attempt to access a file that does not exist on the disk failed.
        ///The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A managed assembly was found but could not be loaded.
        ///The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFileNotLoaded {
            get {
                return ResourceManager.GetString("DialogMessageFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting files or folders are not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFilesNotFoundDelete {
            get {
                return ResourceManager.GetString("DialogMessageFilesNotFoundDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files or folders that move to trash is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFilesNotFoundMoveToTrash {
            get {
                return ResourceManager.GetString("DialogMessageFilesNotFoundMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File disassociation was successful. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageFileUnAssociationSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageFileUnAssociationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file has been encrypted with a higher version.
        ///It can not be decrypted. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageHigherVersion {
            get {
                return ResourceManager.GetString("DialogMessageHigherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   he external configuration file (_AtcCase.ini) was approved for loading, but the approval information could not be saved. The settings will apply only to the current session, and confirmation will be required again after restarting the application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageIniFileApproveFailed {
            get {
                return ResourceManager.GetString("DialogMessageIniFileApproveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   his external configuration file (_AtcCase.ini) was created or approved on a different device. For security reasons, approval is required before using it on this device.
        ///Trust and load this INI file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageIniFileDifferentDevice {
            get {
                return ResourceManager.GetString("DialogMessageIniFileDifferentDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The previously approved external configuration file (_AtcCase.ini) may have been altered or tampered with. For security reasons, re-approval is required before using the modified configuration.
        ///Trust and load the modified INI file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageIniFileModified {
            get {
                return ResourceManager.GetString("DialogMessageIniFileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application will close once due to a series of password entry errors. Please start over from the beginning. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageInputPasswordOverAttempts {
            get {
                return ResourceManager.GetString("DialogMessageInputPasswordOverAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path of files or folders are invalid. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageInvalidFilePath {
            get {
                return ResourceManager.GetString("DialogMessageInvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not the private key of the encrypted pair. Could not decrypt. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageInvalidPrivateKey {
            get {
                return ResourceManager.GetString("DialogMessageInvalidPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A memorized password is currently applied. Proceed with changes?
        ///Decryption may become impossible. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageMemorizedPasswordChange {
            get {
                return ResourceManager.GetString("DialogMessageMemorizedPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No free space on the following disk. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageNoDiskSpace {
            get {
                return ResourceManager.GetString("DialogMessageNoDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is not encrypted file. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageNotAtcFile {
            get {
                return ResourceManager.GetString("DialogMessageNotAtcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not use the folder to the password file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageNotDirectoryInPasswordFile {
            get {
                return ResourceManager.GetString("DialogMessageNotDirectoryInPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is not the same hash value. Whether the file is corrupted, it may have been made the falsification.The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageNotSameHash {
            get {
                return ResourceManager.GetString("DialogMessageNotSameHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following characters cannot be used for the file name of Windows.
        ///
        ///\\ / : , * ? \&quot; &lt; &gt; | に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageNotUseWindowsFileName {
            get {
                return ResourceManager.GetString("DialogMessageNotUseWindowsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now does not correspond to the decryption of password-protected ZIP file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageNotZipDecrypted {
            get {
                return ResourceManager.GetString("DialogMessageNotZipDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting of Windows XP compatibility mode could not be completed. If Setting is not completed, the application can not be started.
        ///Please start again from the beginning. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageNoXpCompatiblityMode {
            get {
                return ResourceManager.GetString("DialogMessageNoXpCompatiblityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There decrypted file is {0} or more.
        ///But, open all of the files associated with application? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageOpenMultipleFiles {
            get {
                return ResourceManager.GetString("DialogMessageOpenMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operating system denied access due to I/O error or 
        ///certain types of security errors. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageOsDeniesAccess {
            get {
                return ResourceManager.GetString("DialogMessageOsDeniesAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encrypted with standard password-based encryption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessagePasswordEncryptionStandard {
            get {
                return ResourceManager.GetString("DialogMessagePasswordEncryptionStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is not found that specified in setting panel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessagePasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessagePasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A password from the password file is currently applied. Proceed with changes?
        ///Decryption may become impossible. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessagePasswordFromPasswordFileChange {
            get {
                return ResourceManager.GetString("DialogMessagePasswordFromPasswordFileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two Passwords do not match, it is invalid.
        ///Input them again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessagePasswordsNotMatch {
            get {
                return ResourceManager.GetString("DialogMessagePasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path name or fully qualified file name exceeds the system-defined maximum length.
        ///The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessagePathTooLong {
            get {
                return ResourceManager.GetString("DialogMessagePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personal Use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessagePersonalUse {
            get {
                return ResourceManager.GetString("DialogMessagePersonalUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Registered に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageRecipientNotRegistered {
            get {
                return ResourceManager.GetString("DialogMessageRecipientNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageRecipientRegistered {
            get {
                return ResourceManager.GetString("DialogMessageRecipientRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following specified text file of registration code can not be found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageRegistrationCodeFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageRegistrationCodeFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not delete registration code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageRegistrationCodeNotDeleted {
            get {
                return ResourceManager.GetString("DialogMessageRegistrationCodeNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The registration code was not successfully registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageRegistrationCodeNotRegistered {
            get {
                return ResourceManager.GetString("DialogMessageRegistrationCodeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A different pair of keys from the RSA-encrypted public key has been specified. Cannot decrypt.
        ///The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageRsaKeyGuidNotMatch {
            get {
                return ResourceManager.GetString("DialogMessageRsaKeyGuidNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send securely without a password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageSendWithoutPassword {
            get {
                return ResourceManager.GetString("DialogMessageSendWithoutPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup tool is not found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageSetupToolNotFound {
            get {
                return ResourceManager.GetString("DialogMessageSetupToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Since it is using temporary settings from command line options, it cannot reflect the main settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageTempSettingsFromCommandLine {
            get {
                return ResourceManager.GetString("DialogMessageTempSettingsFromCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Since it is using temporary settings from INI files, it cannot reflect the main settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageTempSettingsFromIniFile {
            get {
                return ResourceManager.GetString("DialogMessageTempSettingsFromIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reflects the temporarily loaded settings in the registry as the current settings. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageTempSettingsToCurrent {
            get {
                return ResourceManager.GetString("DialogMessageTempSettingsToCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External configuration file (_AtcCase.ini) detected. This file may affect AttacheCase behavior.
        ///Trust and load this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageTrustAndLoadIniFile {
            get {
                return ResourceManager.GetString("DialogMessageTrustAndLoadIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected decrypted files. It stopped the process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageUnexpectedDecryptedFiles {
            get {
                return ResourceManager.GetString("DialogMessageUnexpectedDecryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred. And stops processing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageUnexpectedError {
            get {
                return ResourceManager.GetString("DialogMessageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleAlert {
            get {
                return ResourceManager.GetString("DialogTitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input encrypted file name for putting together に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleAllPackFiles {
            get {
                return ResourceManager.GetString("DialogTitleAllPackFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command Line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleCommandLine {
            get {
                return ResourceManager.GetString("DialogTitleCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select files to encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleEncryptSelectFiles {
            get {
                return ResourceManager.GetString("DialogTitleEncryptSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder to encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleEncryptSelectFolder {
            get {
                return ResourceManager.GetString("DialogTitleEncryptSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleInfomation {
            get {
                return ResourceManager.GetString("DialogTitleInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Question に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleQuestion {
            get {
                return ResourceManager.GetString("DialogTitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleRegistry {
            get {
                return ResourceManager.GetString("DialogTitleRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save a public key and private key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleSavePublicAndPrivateKey {
            get {
                return ResourceManager.GetString("DialogTitleSavePublicAndPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select encrypted files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleSelectEncryptedFiles {
            get {
                return ResourceManager.GetString("DialogTitleSelectEncryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Password file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleSelectPasswordFile {
            get {
                return ResourceManager.GetString("DialogTitleSelectPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleSettings {
            get {
                return ResourceManager.GetString("DialogTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This key is already registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAlreadyRegistered {
            get {
                return ResourceManager.GetString("ErrorAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter an email address. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorEnterEmailAddress {
            get {
                return ResourceManager.GetString("ErrorEnterEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The email address format is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There was a problem generating key data. Please update the application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidKeyData {
            get {
                return ResourceManager.GetString("ErrorInvalidKeyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required information is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMissingFields {
            get {
                return ResourceManager.GetString("ErrorMissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait a while and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRateLimited {
            get {
                return ResourceManager.GetString("ErrorRateLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The recipient does not support hybrid encryption (RSA + ML-KEM) and cannot be encrypted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRecipientNoHybridSupport {
            get {
                return ResourceManager.GetString("ErrorRecipientNoHybridSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A server error occurred (HTTP {0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorServerGeneric {
            get {
                return ResourceManager.GetString("ErrorServerGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorServerStatus {
            get {
                return ResourceManager.GetString("ErrorServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The service is currently busy. Please try again later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorServiceBusy {
            get {
                return ResourceManager.GetString("ErrorServiceBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FluentAccordionItemDetail {
            get {
                return ResourceManager.GetString("FluentAccordionItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the directory to which you save the file or folder to decrypt always. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string folderBrowserDialogSaveToDecryptedFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToDecryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the folder to save the encrypted file always. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string folderBrowserDialogSaveToEncryptedFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToEncryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the folder to save the zip file with password always. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string folderBrowserDialogSaveToZipFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t be changed while loading the configuration file (INI file) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string groupBoxCanNotChange {
            get {
                return ResourceManager.GetString("groupBoxCanNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting file (INI file) option: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string groupBoxReadIniFile {
            get {
                return ResourceManager.GetString("groupBoxReadIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icon_blind {
            get {
                object obj = ResourceManager.GetObject("icon-blind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icon_eye {
            get {
                object obj = ResourceManager.GetObject("icon-eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Encrypt
        ///ATC/EXE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelAtc {
            get {
                return ResourceManager.GetString("LabelAtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    (β Test Version) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelBetaTestVersion {
            get {
                return ResourceManager.GetString("LabelBetaTestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aborted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCaptionAborted {
            get {
                return ResourceManager.GetString("LabelCaptionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skipped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCaptionAllSkipped {
            get {
                return ResourceManager.GetString("LabelCaptionAllSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCaptionCanceled {
            get {
                return ResourceManager.GetString("LabelCaptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCaptionCompleted {
            get {
                return ResourceManager.GetString("LabelCaptionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCaptionError {
            get {
                return ResourceManager.GetString("LabelCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password does not match, it is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCaptionPasswordInvalid {
            get {
                return ResourceManager.GetString("LabelCaptionPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password matches, it is valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCaptionPasswordValid {
            get {
                return ResourceManager.GetString("LabelCaptionPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The code is incorrect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCodeIncorrect {
            get {
                return ResourceManager.GetString("LabelCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Commercial license applicable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCommercialLicenseApplicable {
            get {
                return ResourceManager.GetString("LabelCommercialLicenseApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occured during complete deleting files or folders. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCompleteDeleteError {
            get {
                return ResourceManager.GetString("LabelCompleteDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete deleting files or folder has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCompleteDeleteFileCanceled {
            get {
                return ResourceManager.GetString("LabelCompleteDeleteFileCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files or folders complete deleting is completed normally. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCompleteDeletingCompleted {
            get {
                return ResourceManager.GetString("LabelCompleteDeletingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified files or folders has been deleted Completely. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCompletelyDeleteCompleted {
            get {
                return ResourceManager.GetString("LabelCompletelyDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No compression should be performed on the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCompressMsgNone {
            get {
                return ResourceManager.GetString("LabelCompressMsgNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The compression operation should be optimally compressed, even if the operation takes a longer time to complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCompressMsgOptimal {
            get {
                return ResourceManager.GetString("LabelCompressMsgOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fastest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCompressTitleFastest {
            get {
                return ResourceManager.GetString("LabelCompressTitleFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NoCompression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCompressTitleNone {
            get {
                return ResourceManager.GetString("LabelCompressTitleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NoCompression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCompressTitleNone1 {
            get {
                return ResourceManager.GetString("LabelCompressTitleNone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optimal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCompressTitleOptimal {
            get {
                return ResourceManager.GetString("LabelCompressTitleOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following directory already exists. Do you overwrite the directory to save? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelConfirmToOverwriteDir {
            get {
                return ResourceManager.GetString("LabelConfirmToOverwriteDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following file already exists. Do you overwrite the files to save? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelConfirmToOverwriteFile {
            get {
                return ResourceManager.GetString("LabelConfirmToOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating file list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCreatingFileList {
            get {
                return ResourceManager.GetString("LabelCreatingFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelDec {
            get {
                return ResourceManager.GetString("LabelDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decryption was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelDecryptionCanceled {
            get {
                return ResourceManager.GetString("LabelDecryptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decryption was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelDecyptionCanceled {
            get {
                return ResourceManager.GetString("LabelDecyptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred when deleting files or folders. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelDeleteError {
            get {
                return ResourceManager.GetString("LabelDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bytes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelDeleteMessageBytes {
            get {
                return ResourceManager.GetString("LabelDeleteMessageBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelDeleteTypeRandom {
            get {
                return ResourceManager.GetString("LabelDeleteTypeRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zeros に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelDeleteTypeZeros {
            get {
                return ResourceManager.GetString("LabelDeleteTypeZeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Values of WinZipAes128 and WinZipAes256 are not part of the Zip specification, but rather imply the use of a vendor-specific extension from WinZip. If you want to produce interoperable Zip archives, do not use these values. For example, if you produce a zip archive using WinZipAes256, you will be able to open it in Windows Explorer on Windows XP and Vista, but you will not be able to extract entries; trying this will lead to an &quot;unspecified error&quot;. For this reason, some people have said that a zip archive t [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelEncryptAlgoDescriptionAES {
            get {
                return ResourceManager.GetString("LabelEncryptAlgoDescriptionAES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PkzipWeak implies the use of Zip 2.0 encryption, which is known to be weak and subvertible. 
        ///
        ///A note on interoperability: Values of PkzipWeak and None are specified in PKWARE&apos;s zip specification, and are considered to be &quot;standard&quot;. Zip archives produced using these options will be interoperable with many other zip tools and libraries, including Windows Explorer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelEncryptAlgoDescriptionPkzipWeak {
            get {
                return ResourceManager.GetString("LabelEncryptAlgoDescriptionPkzipWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The encryption process was aborted because the self-executable file could exceed 4GiB. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelEncryptionAbortedToExceed4GiB {
            get {
                return ResourceManager.GetString("LabelEncryptionAbortedToExceed4GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelEncryptionCanceled {
            get {
                return ResourceManager.GetString("LabelEncryptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelError {
            get {
                return ResourceManager.GetString("LabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting ready for decryption... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelGettingReadyForDecryption {
            get {
                return ResourceManager.GetString("LabelGettingReadyForDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting ready for encryption... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelGettingReadyForEncryption {
            get {
                return ResourceManager.GetString("LabelGettingReadyForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input password again to confirm: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelInputPasswordAgainToConfirm {
            get {
                return ResourceManager.GetString("LabelInputPasswordAgainToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of attempts: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelInputPasswordAttempts {
            get {
                return ResourceManager.GetString("LabelInputPasswordAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid character string in path. Do you replace it and decrypt it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelInvalidChar {
            get {
                return ResourceManager.GetString("LabelInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The public or private key was not loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelKeyFileNotLoaded {
            get {
                return ResourceManager.GetString("LabelKeyFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Completely に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabellabelCompletelyDelete {
            get {
                return ResourceManager.GetString("LabellabelCompletelyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to Trash に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelMoveToTrash {
            get {
                return ResourceManager.GetString("LabelMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move files or folders to the trash has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelMoveToTrashCanceled {
            get {
                return ResourceManager.GetString("LabelMoveToTrashCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move files or folders to the trash was completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string labelMoveToTrashCompleted {
            get {
                return ResourceManager.GetString("labelMoveToTrashCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal Deleting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNormalDelete {
            get {
                return ResourceManager.GetString("LabelNormalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting files or folders has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNormalDeleteCanceled {
            get {
                return ResourceManager.GetString("LabelNormalDeleteCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified files or folders has been deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNormalDeleteCompleted {
            get {
                return ResourceManager.GetString("LabelNormalDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password file: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelPasswordFile {
            get {
                return ResourceManager.GetString("LabelPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password file is entered already: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelPasswordFileIsEnteredAlready {
            get {
                return ResourceManager.GetString("LabelPasswordFileIsEnteredAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is incorrect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelPasswordIncorrect {
            get {
                return ResourceManager.GetString("LabelPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discard memorized password and input new password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelPasswordInputNewPassword {
            get {
                return ResourceManager.GetString("LabelPasswordInputNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The memorized password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelPasswordMemorized {
            get {
                return ResourceManager.GetString("LabelPasswordMemorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password of command line option: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelPasswordOfCommandLineOption {
            get {
                return ResourceManager.GetString("LabelPasswordOfCommandLineOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This message will be sent using the standard encryption method.
        ///A password must be shared after sending the encrypted file.
        ///
        ///For recipients with a registered email address, files can be sent without a password.
        ///
        ///Drag and drop files or folders to encrypt here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelPasswordSharingRequired {
            get {
                return ResourceManager.GetString("LabelPasswordSharingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Secure File
        ///Sharing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelPostPpap {
            get {
                return ResourceManager.GetString("LabelPostPpap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete completely is completed successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelProcessDeleteCompletely {
            get {
                return ResourceManager.GetString("LabelProcessDeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting ready for encryption... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelProcessGettingRedyForEncryption {
            get {
                return ResourceManager.GetString("LabelProcessGettingRedyForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrypting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelProcessNameDecrypt {
            get {
                return ResourceManager.GetString("LabelProcessNameDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelProcessNameDelete {
            get {
                return ResourceManager.GetString("LabelProcessNameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting Completely... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelProcessNameDeleteCompletely {
            get {
                return ResourceManager.GetString("LabelProcessNameDeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encrypting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelProcessNameEncrypt {
            get {
                return ResourceManager.GetString("LabelProcessNameEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to Trash... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelProcessNameMoveToTrash {
            get {
                return ResourceManager.GetString("LabelProcessNameMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipient&apos;s email address: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRecipientEmailAddress {
            get {
                return ResourceManager.GetString("LabelRecipientEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Public-key
        ///cryptography に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRsa {
            get {
                return ResourceManager.GetString("LabelRsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag and drop the file or folder you want to encrypt or decrypt here. You can also drag and drop the public key and private key first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRsaDescription {
            get {
                return ResourceManager.GetString("LabelRsaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The encrypted file has been loaded. Drag and drop the private key to be decrypted here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRsaEncryptedFileloaded {
            get {
                return ResourceManager.GetString("LabelRsaEncryptedFileloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file or folder has been loaded. Drag and drop public key to be encrypted here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRsaFilesloaded {
            get {
                return ResourceManager.GetString("LabelRsaFilesloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This key is not RSA-4096. Only RSA-4096 keys are supported in this version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRsaKeyTooSmall {
            get {
                return ResourceManager.GetString("LabelRsaKeyTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag and drop the file or folder you want to encrypt or decrypt here. You can also drag and drop the public key and private key first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRsaMessage {
            get {
                return ResourceManager.GetString("LabelRsaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Private Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRsaPrivateKey {
            get {
                return ResourceManager.GetString("LabelRsaPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The private key has been loaded. Drag and drop the encrypted file to be decrypted here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRsaPrivateKeyloaded {
            get {
                return ResourceManager.GetString("LabelRsaPrivateKeyloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Public Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRsaPublicKey {
            get {
                return ResourceManager.GetString("LabelRsaPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The public key has been loaded. Drag and drop the ​file or folder to be encrypted here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRsaPublicKeyloaded {
            get {
                return ResourceManager.GetString("LabelRsaPublicKeyloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The search has been canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelSearchCanceled {
            get {
                return ResourceManager.GetString("LabelSearchCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register your email address to allow others to send files securely
        ///
        ///• Files are encrypted using your information before sending
        ///• Decryption is performed only on this device
        ///• Your email address is stored in encrypted form and cannot be viewed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelSecureReceiveSetupDescription {
            get {
                return ResourceManager.GetString("LabelSecureReceiveSetupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valid code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelValidCode {
            get {
                return ResourceManager.GetString("LabelValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email address: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelYourEmailAddress {
            get {
                return ResourceManager.GetString("LabelYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The compression operation should complete as quickly as possible, even if the resulting file is not optimally compressed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LbelCompressMsgFastest {
            get {
                return ResourceManager.GetString("LbelCompressMsgFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting updates information is failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LinkLabelCheckForUpdatesFailed {
            get {
                return ResourceManager.GetString("LinkLabelCheckForUpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking for update... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LinkLabelCheckingForUpdates {
            get {
                return ResourceManager.GetString("LinkLabelCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your version is latest. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LinkLabelLatestVersion {
            get {
                return ResourceManager.GetString("LinkLabelLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The latest version is released! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LinkLabelLatestVersionReleased {
            get {
                return ResourceManager.GetString("LinkLabelLatestVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Abort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxButtonAbort {
            get {
                return ResourceManager.GetString("MessageBoxButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxButtonCancel {
            get {
                return ResourceManager.GetString("MessageBoxButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Proceed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxButtonProceed {
            get {
                return ResourceManager.GetString("MessageBoxButtonProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More Info:
        ///To ensure that the file is decrypted correctly, the unique value (MD5 hash) of the original file is written to the file before encryption and is checked during decryption.
        ///
        ///- Encrypted file hash value: {0}
        ///- File hash value after decryption: {1}.
        ///
        ///If these hash values do not match, the file may have been modified from its original state or corrupted. Please use this information to determine if you wish to proceed with decryption. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxDetailedInformation {
            get {
                return ResourceManager.GetString("MessageBoxDetailedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to verify the following file. The files may have been modified or corrupted. How do I proceed? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxFileVerifyFailed {
            get {
                return ResourceManager.GetString("MessageBoxFileVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide &amp;Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxHideDetails {
            get {
                return ResourceManager.GetString("MessageBoxHideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show&amp;Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxShowDetails {
            get {
                return ResourceManager.GetString("MessageBoxShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenDialogFilterAllFiles {
            get {
                return ResourceManager.GetString("OpenDialogFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon files(*.ico)|*.ico|All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenDialogFilterIconFiles {
            get {
                return ResourceManager.GetString("OpenDialogFilterIconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Icon files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenDialogTitleIconFiles {
            get {
                return ResourceManager.GetString("OpenDialogTitleIconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation email sent
        ///Please click the link in the email に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressMessageConfirmationEmailSent {
            get {
                return ResourceManager.GetString("ProgressMessageConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter email address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressMessageEnterEmailAddress {
            get {
                return ResourceManager.GetString("ProgressMessageEnterEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressMessageRegistrationCanceled {
            get {
                return ResourceManager.GetString("ProgressMessageRegistrationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressMessageRegistrationComplete {
            get {
                return ResourceManager.GetString("ProgressMessageRegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending confirmation email... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressMessageSendingConfirmationEmail {
            get {
                return ResourceManager.GetString("ProgressMessageSendingConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timed out
        ///Please try again に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressMessageTimeout {
            get {
                return ResourceManager.GetString("ProgressMessageTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ATC files (*.atc)|*.atc|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveDialogFilterAtcFiles {
            get {
                return ResourceManager.GetString("SaveDialogFilterAtcFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INI files (*.ini)|*.ini|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveDialogFilterIniFilles {
            get {
                return ResourceManager.GetString("SaveDialogFilterIniFilles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Self Executable file(*.exe)|*.exe|All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveDialogFilterSelfExeFiles {
            get {
                return ResourceManager.GetString("SaveDialogFilterSelfExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vulnerable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnLabel00 {
            get {
                return ResourceManager.GetString("ZxcvbnLabel00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weak に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnLabel01 {
            get {
                return ResourceManager.GetString("ZxcvbnLabel01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Somewhat weak に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnLabel02 {
            get {
                return ResourceManager.GetString("ZxcvbnLabel02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Good に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnLabel03 {
            get {
                return ResourceManager.GetString("ZxcvbnLabel03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strong に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnLabel04 {
            get {
                return ResourceManager.GetString("ZxcvbnLabel04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty string に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnLabelEmpty {
            get {
                return ResourceManager.GetString("ZxcvbnLabelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add another word or two. Uncommon words are better. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionAddAnotherWordOrTwo {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionAddAnotherWordOrTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All-uppercase is almost as easy to guess as all-lowercase. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionAllCapsEasy {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionAllCapsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid dates and years that are associated with you. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionAvoidDatesYearsAssociatedYou {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionAvoidDatesYearsAssociatedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid repeated words and characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionAvoidRepeatedWordsAndChars {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionAvoidRepeatedWordsAndChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid sequences. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionAvoidSequences {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionAvoidSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid recent years. Avoid years that are associated with you. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionAvoidYearsAssociatedYou {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionAvoidYearsAssociatedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capitalization doesn&apos;t help very much. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionCapsDontHelp {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionCapsDontHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use a few words, avoid common phrases. No need for symbols, digits, or uppercase letters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionDefault {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionEmpty {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Predictable substitutions like &apos;@&apos; instead of &apos;a&apos; don&apos;t help very much. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionPredictableSubstitutionsEasy {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionPredictableSubstitutionsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reversed words aren&apos;t much harder to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionReversedWordEasy {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionReversedWordEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use a longer keyboard pattern with more turns. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnSuggestionUseLongerKeyboardPattern {
            get {
                return ResourceManager.GetString("ZxcvbnSuggestionUseLongerKeyboardPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnToolTipTitleSuggestions {
            get {
                return ResourceManager.GetString("ZxcvbnToolTipTitleSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnToolTipTitleWarning {
            get {
                return ResourceManager.GetString("ZxcvbnToolTipTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dates are often easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarnigDatesEasy {
            get {
                return ResourceManager.GetString("ZxcvbnWarnigDatesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common names and surnames are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningCommonNameSurnamesEasy {
            get {
                return ResourceManager.GetString("ZxcvbnWarningCommonNameSurnamesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is a very common password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningCommonPasswords {
            get {
                return ResourceManager.GetString("ZxcvbnWarningCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dates are often easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningDatesEasy {
            get {
                return ResourceManager.GetString("ZxcvbnWarningDatesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningDefault {
            get {
                return ResourceManager.GetString("ZxcvbnWarningDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty String. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningEmpty {
            get {
                return ResourceManager.GetString("ZxcvbnWarningEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Names and surnames by themselves are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningNameSurnamesEasy {
            get {
                return ResourceManager.GetString("ZxcvbnWarningNameSurnamesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent years are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningRecentYearsEasy {
            get {
                return ResourceManager.GetString("ZxcvbnWarningRecentYearsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeats like &apos;aaa&apos; are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningRepeatsLikeAaaEasy {
            get {
                return ResourceManager.GetString("ZxcvbnWarningRepeatsLikeAaaEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeats like &apos;abcabcabc&apos; are only slightly harder to guess than &apos;abc&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningRepeatsLikeAbcSlighterHarder {
            get {
                return ResourceManager.GetString("ZxcvbnWarningRepeatsLikeAbcSlighterHarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sequences like abc or 6543 are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningSequenceAbcEasy {
            get {
                return ResourceManager.GetString("ZxcvbnWarningSequenceAbcEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short keyboard patterns are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningShortKeyboardPatterns {
            get {
                return ResourceManager.GetString("ZxcvbnWarningShortKeyboardPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is similar to a commonly used password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningSimilarCommonPasswords {
            get {
                return ResourceManager.GetString("ZxcvbnWarningSimilarCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Straight rows of keys are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningStraightRow {
            get {
                return ResourceManager.GetString("ZxcvbnWarningStraightRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is a top-10 common password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningTop10Passwords {
            get {
                return ResourceManager.GetString("ZxcvbnWarningTop10Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A word by itself is easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZxcvbnWarningWordEasy {
            get {
                return ResourceManager.GetString("ZxcvbnWarningWordEasy", resourceCulture);
            }
        }
    }
}
